# Production Docker Compose Configuration
# This version uses Docker secrets for enhanced security

version: '3.8'

services:
  vcoin-front:
    build: 
      context: .
      dockerfile: Dockerfile
    image: vcoin:1.0.0
    container_name: vcoin
    ports:
      - "3000:3000"
    environment:
      # Application Configuration
      - NODE_ENV=production
      
      # Timezone Configuration
      - TZ=America/Argentina/Buenos_Aires
      
      # Database Configuration - Using secrets
      - DB_HOST_FILE=/run/secrets/db_host
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-vcoin}
      - DB_USER_FILE=/run/secrets/db_user
      - DB_PASSWORD_FILE=/run/secrets/db_password
      
      # Next.js Configuration
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      
      # NextAuth.js Configuration - Using secrets
      - NEXTAUTH_SECRET_FILE=/run/secrets/nextauth_secret
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      
      # Student Session Security - Using secrets
      - SESSION_SECRET_FILE=/run/secrets/session_secret
      
      # Google OAuth2 Configuration - Using secrets
      - GOOGLE_CLIENT_ID_FILE=/run/secrets/google_client_id
      - GOOGLE_CLIENT_SECRET_FILE=/run/secrets/google_client_secret
      
      # Login Throttling Configuration
      - LOGIN_THROTTLE_MIN_DELAY=${LOGIN_THROTTLE_MIN_DELAY:-1000}
      - LOGIN_THROTTLE_MAX_DELAY=${LOGIN_THROTTLE_MAX_DELAY:-30000}
      - LOGIN_THROTTLE_MAX_TRACKED=${LOGIN_THROTTLE_MAX_TRACKED:-10000}
      - LOGIN_THROTTLE_RESET_TIME=${LOGIN_THROTTLE_RESET_TIME:-300000}
      - LOGIN_THROTTLE_CLEANUP_INTERVAL=${LOGIN_THROTTLE_CLEANUP_INTERVAL:-60000}
    
    secrets:
      - db_host
      - db_user
      - db_password
      - nextauth_secret
      - session_secret
      - google_client_id
      - google_client_secret
    
    restart: unless-stopped
    
    # Security configurations
    security_opt:
      - no-new-privileges:true
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    
    # Network isolation
    networks:
      - vcoin-network

# Docker secrets configuration
secrets:
  db_host:
    external: true
    name: vcoin_db_host
  db_user:
    external: true
    name: vcoin_db_user
  db_password:
    external: true
    name: vcoin_db_password
  nextauth_secret:
    external: true
    name: vcoin_nextauth_secret
  session_secret:
    external: true
    name: vcoin_session_secret
  google_client_id:
    external: true
    name: vcoin_google_client_id
  google_client_secret:
    external: true
    name: vcoin_google_client_secret

# Network configuration
networks:
  vcoin-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
