services:
  vcoin-front:
    build: 
      context: .
      dockerfile: Dockerfile
    image: vcoin-front:latest
    container_name: vcoin-front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
